import fs from 'node:fs';
import zlib from 'node:zlib';
const files=['index.html','styles.css','app.js','src/app/main.js','src/core.js','src/data/firebase-client.js','src/data/firebase-repository.js','src/app/ui.js','src/app/radar-view.js','src/features/places/place-view.js','src/features/recommendations/recommendation-view.js','src/features/expenses/expense-view.js'];
const size=f=>fs.statSync(f).size,gzip=f=>zlib.gzipSync(fs.readFileSync(f),{level:9}).length;
const budgets={'styles.css':34000,'src/app/main.js':39000,'src/core.js':22000,'src/data/firebase-client.js':9000,'src/data/firebase-repository.js':18000};
for(const [file,max] of Object.entries(budgets))if(size(file)>max)throw new Error(`perf: ${file} ${size(file)} B exceeds ${max} B budget`);
const html=fs.readFileSync('index.html','utf8');
if(/<script[^>]+src="https?:\/\//.test(html)||/<link[^>]+href="https?:\/\//.test(html))throw new Error('perf: external blocking runtime assets are not allowed');
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]),dup=ids.filter((id,i)=>ids.indexOf(id)!==i);if(dup.length)throw new Error(`perf: duplicate DOM ids: ${[...new Set(dup)].join(', ')}`);
const totalRaw=files.reduce((sum,f)=>sum+size(f),0),totalGzip=files.reduce((sum,f)=>sum+gzip(f),0);
console.log(`perf-check: ${files.length} critical/local assets · ${totalRaw} B raw · ${totalGzip} B gzip-equivalent · Firebase SDK lazy-loaded only in prod`);
