import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('styles.css','utf8'),main=fs.readFileSync('src/app/main.js','utf8'),core=fs.readFileSync('src/core.js','utf8'),rules=fs.readFileSync('firebase/firestore.rules','utf8');
for(const id of ['homeTitle','addBtn','placesList','placeDialog','radiusSelect','radarSvg','expenseList','backToTop','authGate','googleLoginBtn'])if(!html.includes(`id="${id}"`))throw new Error(`Smoke failed: missing #${id}`);
for(const symbol of ['filterAndSortPlaces','googleMapsCoordinateUrl','sanitizeExpense'])if(!core.includes(symbol))throw new Error(`Smoke failed: core missing ${symbol}`);
for(const file of ['src/data/firebase-client.js','src/data/firebase-repository.js','firebase/firestore.rules','firebase.json','data/default-places.json','api/config.js'])if(!fs.existsSync(file))throw new Error(`Smoke failed: missing ${file}`);
if((css.match(/!important/g)||[]).length)throw new Error('Smoke failed: CSS !important debt returned');
if(!main.includes("dataConfig.provider === 'firebase'")||!main.includes('updateLocalModeUi'))throw new Error('Smoke failed: environment provider switch missing');
if(!main.includes("import('/src/data/firebase-client.js')"))throw new Error('Smoke failed: Firebase is not lazy-loaded');
if(!rules.includes('match /places/{placeId}')||!rules.includes('request.auth.uid')||!rules.includes("role(tripId) == 'owner'"))throw new Error('Smoke failed: Firestore RBAC rules missing');
if(!JSON.parse(fs.readFileSync('vercel.json','utf8')).headers)throw new Error('Smoke failed: Vercel security headers missing');
if(!css.includes('@media (max-width: 360px)')||!css.includes('font-size: 40px'))throw new Error('Smoke failed: small-phone guards missing');
if(!html.includes('property="og:title"')||!html.includes('type="application/ld+json"'))throw new Error('Smoke failed: SEO markup missing');
console.log('smoke: localStorage/Firebase switch, Firestore RBAC, responsive UI, SEO and security guards passed');
