import fs from 'node:fs';
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('styles.css','utf8'),app=fs.readFileSync('app.js','utf8'),main=fs.readFileSync('src/app/main.js','utf8');
const modules=['src/app/ui.js','src/app/storage.js','src/app/radar-view.js','src/app/demo-seed.js','src/app/app-shell.js','src/data/firebase-client.js','src/data/firebase-repository.js'].map(f=>[f,fs.readFileSync(f,'utf8')]);
const assert=(ok,msg)=>{if(!ok)throw new Error(`UI check failed: ${msg}`)},has=re=>re.test(css);
assert(!html.includes('section-caret'),'collapse icons must stay removed');
assert(html.includes('<body class="app-booting">')&&html.includes('id="bootGate"'),'auth-safe boot shell missing');
assert(css.includes('body.app-booting .topbar')&&css.includes('body.app-auth-required .shell'),'protected UI flash guard missing');
assert((css.match(/!important/g)||[]).length===0,'CSS must not use !important overrides');
assert(has(/body\s*\{[^}]*overflow-x:\s*clip/s),'body horizontal overflow guard missing');
assert(css.includes('@media (max-width: 820px)')&&css.includes('@media (max-width: 480px)')&&css.includes('@media (max-width: 360px)'),'mobile breakpoints missing');
assert(has(/dialog\s*\{[^}]*width:\s*100vw[^}]*max-width:\s*100vw[^}]*max-height:\s*92dvh/s),'mobile dialog viewport guard missing');
assert(has(/\.places-list\s*\{[^}]*max-height:\s*520px[^}]*overflow:\s*auto/s),'mobile places bounded scroll missing');
assert(has(/\.expense-list\s*\{[^}]*max-height:\s*430px[^}]*overflow:\s*auto/s),'mobile expenses bounded scroll missing');
assert(has(/\.row-actions\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/s),'place actions must stay one horizontal row');
assert(has(/@media\s*\(max-width:\s*820px\)[\s\S]*?\.hero-card\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/s),'mobile Home Base must stack instead of overflow');
assert(has(/\.route-meta\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)[^}]*align-items:\s*stretch/s),'base/desktop route meta must use three balanced stretched columns');
assert(has(/\.route-meta\s*>\s*\.route-pill,[\s\S]*?\.route-meta\s*>\s*\.vote-btn\s*\{[^}]*height:\s*34px[^}]*align-items:\s*center[^}]*justify-content:\s*center/s),'base/desktop route meta items must share equal height and centering');
assert(has(/@media\s*\(max-width:\s*820px\)[\s\S]*?\.route-meta\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/s),'mobile route meta must use three balanced columns');
assert(has(/@media\s*\(max-width:\s*820px\)[\s\S]*?\.home-actions\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)[^}]*gap:\s*7px/s),'mobile Home actions must use three equal columns');
assert(has(/@media\s*\(max-width:\s*820px\)[\s\S]*?\.home-actions button\s*\{[^}]*height:\s*38px[^}]*align-items:\s*center[^}]*justify-content:\s*center/s),'mobile Home actions must share equal height and centering');
assert(css.includes('align-items: stretch;') && css.includes('grid-template-columns: repeat(3, minmax(0, 1fr));'),'mobile route meta must stretch three balanced columns');
assert(has(/@media\s*\(max-width:\s*820px\)[\s\S]*?\.route-meta > \.route-pill,[\s\S]*?\.route-meta > \.vote-btn\s*\{[^}]*height:\s*34px[^}]*align-items:\s*center[^}]*justify-content:\s*center/s),'mobile route pills and vote must share equal height and centering');
assert(has(/@media\s*\(max-width:\s*820px\)[\s\S]*?\.place-row\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/s),'mobile place card must not reserve a narrow distance column');
assert(has(/\.cluster-places\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/s),'cluster details must use two-column layout');
assert(css.includes('.radar-place:hover .radar-place-label')&&css.includes('.radar-sweep'),'radar treatment missing');
assert(has(/@media\s*\(max-width:\s*480px\)[\s\S]*?font-size:\s*40px/s),'mobile H1 must remain 40px');
assert(main.includes("dataConfig.provider === 'firebase'")&&main.includes('DATA_PROVIDER_LOCAL'),'environment provider switch missing');
assert(main.includes("import('/src/data/firebase-client.js')"),'Firebase must be lazy-loaded only for prod');
assert(Buffer.byteLength(css)<34000,`CSS budget exceeded (${Buffer.byteLength(css)} bytes)`);assert(Buffer.byteLength(app)<1000,'bootstrap app.js too large');assert(Buffer.byteLength(main)<39000,'main.js too large');
for(const [f,c] of modules)assert(Buffer.byteLength(c)<19000,`${f} module budget exceeded`);
console.log(`ui-check: responsive + local/prod provider invariants passed; CSS ${Buffer.byteLength(css)} B, 0 !important`);
